name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Build the OrderService
        run: dotnet build ./OrderService/OrderService.csproj
      - name: Build the InventoryService
        run: dotnet build ./InventoryService/InventoryService.csproj

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Azure App Service (if applicable)
        # Add deployment steps for your chosen cloud
